mode = "dark"
base00 = "2e3440"
base01 = "3b4252"
base02 = "434c5e"
base03 = "4c566a"
base04 = "d8dee9"
base05 = "e5e9f0"
base06 = "eceff4"
base07 = "8fbcbb"
base08 = "88c0d0"
base09 = "81a1c1"
base0A = "5e81ac"
base0B = "bf616a"
base0C = "d08770"
base0D = "ebcb8b"
base0E = "a3be8c"
base0F = "b48ead"
